public class testinvocable {
    @InvocableMethod(label='Welcome Message' description = 'This is display the welcome message' category='Welcome')
    Public static List<string> vcx(){
    List<google_credential__mdt> mcs = google_credential__mdt.getAll().values();
     
        list<string> abc=new list<string>();
            string texta='Id new';
             string tecx='acxz';
        String orgId = UserInfo.getOrganizationId();
    
        abc.add(texta);
        abc.add(tecx);
       
        return abc;}
    

}